name: Publish to PyPI

on:
  push:
    tags:
      - "v*"

permissions:
  id-token: write  # required for trusted publishing
  contents: read

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install build
      - run: python -m build

      - name: Publish (Trusted Publishing)
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          attestations: true
          skip-existing: true
