name: Publish to PyPI

on:
  push:
    tags: ["v*"]   # only run when you push a tag like v0.1.4

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Build dists
        run: |
          python -m pip install -U build
          python -m build

      - name: Twine check
        run: |
          python -m pip install -U twine
          twine check dist/*

      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}
